Repository KyoriPowered/blossom, pull requests merged in 2023-09, with the labels that each got.

#27 fix: Correct inverted header newline condition
  src/workerClasspath/java/net/kyori/blossom/internal/worker/GenerateWorkerInvokerImpl.java
Labels: bug

#36 Fix included files
  src/test/java/net/kyori/blossom/IncludedMacrosTest.java
  src/test/resources/net/kyori/blossom/includedMacros/in/build.gradle
  src/test/resources/net/kyori/blossom/includedMacros/in/macros.peb
  src/test/resources/net/kyori/blossom/includedMacros/in/macros1.peb
  src/test/resources/net/kyori/blossom/includedMacros/in/test.properties.peb
  src/workerClasspath/java/net/kyori/blossom/internal/worker/GenerateWorkerInvokerImpl.java
  src/workerClasspath/java/net/kyori/blossom/internal/worker/MultiDirectoryLoader.java
Labels: type: bug

#37 Add default `variant` template property when using variants
  readme.md
  src/workerClasspath/java/net/kyori/blossom/internal/worker/PropertyFileIO.java
Labels: type: enhancement

#38 feat: Add helper API to make it easier to register custom sets
  src/main/java/net/kyori/blossom/BlossomExtension.java
Labels: type: enhancement
